export const GET_STATS = "GET_STATS";
export const GET_COUNTRIES = "GET_COUNTRIES";
export const GET_LIST_OF_REGIONS = "GET_LIST_OF_REGIONS";
export const GET_REGION_STATS = "GET_REGION_STATS";
export const GET_DAILY_STATS = "GET_DAILY_STATS";
